Microsoft.Extensions.ServiceDiscovery support
nacos-group/nacos-sdk-csharp pull request #317
Opened 2024-09-17 12:56 UTC by ZUOXIANGE

做了一点微小的工作

2024-09-17 12:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-sdk-csharp?pullRequest=317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-sdk-csharp?pullRequest=317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-sdk-csharp?pullRequest=317) it.</sub>

2024-09-19 01:18 UTC, catcherwong requested changes
感谢 PR

有几个小问题和疑问。

另外，能否补充一些简单的单元测试或集成测试。

2024-09-19 01:18 UTC, catcherwong commented on src/Nacos.Microsoft.Extensions.ServiceDiscovery/NacosServiceEndpointProviderBase.Log.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
这个可能要改一下

2024-09-19 01:18 UTC, catcherwong commented on src/Nacos.Microsoft.Extensions.ServiceDiscovery/NacosServiceEndpointProviderBase.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
同上

2024-09-19 01:18 UTC, catcherwong commented on samples/App3/Program.cs
Sample 能否独立一个新的项目？

2024-09-19 01:18 UTC, catcherwong commented on src/Nacos.Microsoft.Extensions.ServiceDiscovery/NacosServiceEndPointProvider.cs
> +        var selectInstances = await namingService.SelectInstances(hostName, true).ConfigureAwait(false);
这里是定期主动去查，不考虑同时订阅吗？这样服务实例变化会有主动的通知过来。

2024-09-19 03:45 UTC, ZUOXIANGE commented on samples/App3/Program.cs
这个没有必要吧,正好复用请求到app1,但是有个问题,因为serviceName是通过uri.Host获取的,所以只能支持小写,在测试使用的时候需要把app1注册的serviceName改为小写

2024-09-19 04:47 UTC, ZUOXIANGE commented on src/Nacos.Microsoft.Extensions.ServiceDiscovery/NacosServiceEndPointProvider.cs
> +        var selectInstances = await namingService.SelectInstances(hostName, true).ConfigureAwait(false);
我实现的时候有注意到这个问题,只是不知道怎么合理的去改变_lastChangeToken的HasChanged的值,所以没有实现

2024-09-20 01:14 UTC, catcherwong requested changes

2024-09-20 01:14 UTC, catcherwong commented on src/Nacos.Microsoft.Extensions.ServiceDiscovery/NacosServiceEndpointProviderOptions.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
这个还没改过来

2024-09-20 02:54 UTC, catcherwong approved these changes

2024-09-20 02:54 UTC, merged

2024-10-15 02:09 UTC, ROMYIM commented
问个小问题。
我看了下`ServiceEndpointQuery`的源码，他是通过`Uri`工具类转换，再解析成`ServiceName`，`EndpointName`等参数。但是通过Uri转换会有个问题，就是会把原始的字符串变成小写。比如，我的uri是http://CommonService/，它解析完后的ServiceName就是commonservice。
然后我又看了`ServiceEndpointProvider`的源码，它是通过`INamingService.SelectInstances(serviceName, healthy)`获取实例信息。
问题一：`INamingService.SelectInstances(serviceName, healthy)`中的serviceName支持忽略大小写匹配吗？ @catcherwong 
问题二：如果问题一的答案是不支持，那么如果我注册的服务名称包含大写，那么服务发现怎么获取到我的实例信息呢？ @ZUOXIANGE

2024-10-15 05:53 UTC, ZUOXIANGE commented
https://github.com/nacos-group/nacos-sdk-csharp/pull/317#discussion_r1766107380  正如我这里提到的,只能把服务名改为小写
@ROMYIM

2024-10-15 06:07 UTC, ROMYIM commented
那么`INamingService`中关于根据服务名称获取实例信息的接口可不可以添加忽略大小写的选项开关
@catcherwong

2024-10-20 15:46 UTC, catcherwong commented
客户端做不到忽略大小写的，毕竟这个是要从服务端取数据的。